### ISSUE TITLE
Null Pointer Exceptions on the Galaxy S-range

### ISSUE THREAD

**Issue by dixonary** [fbricker/openfl-gpg#7]
Hello,

I have had 4 total reports of crashes in my newly released application. Three of those have been on Galaxy S3 Mini devices, and one on a Galaxy S2. Admittedly this is a small sample range so this could be coincidence, but I do not own the devices and so cannot do much digging around.

However, two people were nice enough to submit ANR reports through the Google feedback mechanism, and I have attached the crash reports.

java.lang.NullPointerException
at com.gpgex.GooglePlayGames$1.run(GooglePlayGames.java:42)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4867)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)

java.lang.NullPointerException
at com.gpgex.GooglePlayGames$1.run(GooglePlayGames.java:42)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4921)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)

**Comment by fbricker** [comment]
Hi, can you tell me which android version they had?
Also, you can check that you have the last version of:
- openfl-gpg library
- google play services lib (from android manager)
- openfl
- lime

It's strange since I have 4 games using this library and this is the first time I see those reports. Maybe it's something related to the devices or some outdated library.

Thanks!

**Comment by dixonary** [comment]
In all cases it was 4.1, and I definitely have the latest versions of all
the relevant libraries & tools.

Best wishes

**Comment by fbricker** [comment]
Mmm, I'll try to get some android 4.1 device to test it on device. I only have one, but it has Cyanogen, so I don't think is a good / standard environment to test.

If you can have access to one of those devices for testing, it'll be good to have some more debugging :)

Anyway, by the log message I guess this happened when the app was launched (most probably during the initialization / linking on Java methods with JNI). Maybe I should not initialize them in the static declaration, and initialize them during the init method call (just in case).

At least, this way, I'll be able to catch the JNI exception and display some more information :)

**Comment by fbricker** [comment]
I've just published version 1.2.2 that inits the library on a different way. I assume this will avoid this problem (but I can't know for sure since I wasn't able to replicate it on the first place).

Thanks for reporting!
